<?php
include "template/top.php"
?>	
	<!--RANKING-->
	<div id="ranking">
		<h1>Ranking</h1>
		<div id="ranking-nome">
			<form action="" method="">
				<label>Procurar por jogador:</label>
				<input type="text" name="" placeholder="Pesquisar">
			</form>
		</div>
		<div id="ranking-filtro">
			<form>
				<label>Escolha o tipo de ranking:</label>
				<select name="">
					<option name="">Level</option>
					<option name="">Gold</option>
					<option name="">Geral</option>
				</select>
			</form action="" method="">
		</div>
		<div id="ranking-tabela">
			<table border="1">
				<tr>
					<th>Posição</th>
					<th>Nome</th>
					<th>Casa</th>
					<th>Gold</th>
					<th>Level</th>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>
				<tr>
					<td>1º</td>
					<td>Player</td>
					<td>Targaryen</td>
					<td>10.000.000</td>
					<td>99</td>
				</tr>

			</table>
		</div>
	</div><!--FIM RANKING-->
	<!--PAGINATOR-->
	<div id="paginator-ranking">
		<a href="#">&laquo</a>
		<a href="#">1</a>
		<a href="#">2</a>
		<a href="#">3</a>
		<a href="#">&raquo</a>
	</div><!--PAGINATOR-->
<?php
include "template/bottom.php"
?>